const RESPONSE_ERROR_SQL_GENERAL = "ERR_SQL_GEN";
const RESPONSE_ERROR_SQL_NO_CONNECTION = "ERR_SQL_NO_CONN";
const RESPONSE_ERROR_SQL_BAD_QUERY = "ERR_SQL_BAD_QUERY";

const RESPONSE_ERROR_NOT_LOGGED_IN = "ERR_LOGIN_NEEDED";
const RESPONSE_ERROR_INSUFFICIENT_PERMISSION = "ERR_INSUFF_PERM";

const RESPONSE_ERROR_VARIABLES_MISSING = "ERR_VAR_MISSING";
const RESPONSE_ERROR_VARIABLES_INVALID = "ERR_VAR_INVALID";

const RESPONSE_SUCCESS = "SUCCESS";
